# Generated by Django 3.0.7 on 2020-06-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='undefine@ex.com', max_length=50),
            preserve_default=False,
        ),
    ]
